[TASK] Prepare the 8.4.1 release
sabberworm/PHP-CSS-Parser pull request #419
Opened 2024-01-19 18:35 UTC by oliverklee

I have compiled the changes that seemed relevant from the git history.

2024-01-20 01:46 UTC, JakeQZ reviewed
I'm struggling to understand this.  I can't see any changes made since 8.4.0 apart from dependabot.  Was 8.4.0 release made from a separate branch?  If so, which branch?

2024-01-20 08:30 UTC, oliverklee commented
I think I see now where the confusion comes from. :sli


I created the 8.4.0 release (or better, the [8.4.0 release documentation on GitHub](https://github.com/sabberworm/PHP-CSS-Parser/releases/tag/8.4.0)) yesterday because it was missing. Version 8.4.0 had actually been released (i.e., git-tagged, which is what is relevant for Packagist/Composer) [on December 11th](https://github.com/sabberworm/PHP-CSS-Parser/tags).

You can list the commits since the 8.4.0 tag with this command:

```bash
git log 8.4.0..HEAD
```

I've done my best to make sense of the commits and compile them into the changelog. (For the future, I'd like us to directly add the changelog entries together with their corresponding PRs.)

2024-01-20 08:30 UTC, oliverklee commented
Oh, and the 8.4.0 released was tagged from this repo's default branch, i.e., `master`, I think.

2024-01-23 19:14 UTC, JakeQZ requested changes
> Version 8.4.0 had actually been released (i.e., git-tagged, which is what is relevant for Packagist/Composer) [on December 11th](https://github.com/sabberworm/PHP-CSS-Parser/tags).

Ah.  I see now.

> Oh, and the 8.4.0 released was tagged from this repo's default branch, i.e., `master`, I think.

I've gone through the commits since 8.4.0 and believe I've found 3 more fixes and one additional feature.  I've also found the PR numbers for the items you added to the changelog without one.  The other items you added seem correct.

Given there has actually been one new feature since 8.4.0 (#384), should the next release in fact be 8.5.0?

2024-01-23 19:14 UTC, JakeQZ commented on CHANGELOG.md
> +- Add more unit tests
The unit test additions had PR numbers #381 and #382.

2024-01-27 20:00 UTC, oliverklee commented
Done and repushed.

2024-02-01 00:39 UTC, JakeQZ approved these changes
All looks good now.

Sorry for delay in re-review - I didn't get any email notification (though did about the original PR, and also received a couple of other GitHub notification emails on the same day).

2024-02-01 00:40 UTC, merged

2024-02-01 00:41 UTC, JakeQZ commented
Auto-deletion of merged branches appears not to be enabled.

2024-02-01 00:45 UTC, JakeQZ commented
Also, I didn't see the 'Squash-and-Merge' option, 'Merge Branch' was the default, but maybe I should have looked for a dropdown on the button to change it - can't remember now if there was one.

2024-02-01 07:12 UTC, sabberworm commented
@JakeQZ @oliverklee thank you both so much!

2024-02-01 09:25 UTC, oliverklee commented
I've just tagged and released the new version: https://github.com/sabberworm/PHP-CSS-Parser/releases/tag/8.5.0